### ISSUE TITLE
"The impossible happened!"

### ISSUE THREAD

**Issue by samuela** [ollef/Bidirectional#2]
Attempting to synthesize a type of `(λx. x x)` fails for obvious reasons, but attempting to synthesize the type with a type annotation -- `λx. (x : ∀ a. a → a) x` -- produces a "The impossible has happened!" error. Consider the following ghci session:

```haskell
*Main> let ty = polytype $ TForall (TypeVar "a") (TFun (tvar "a") (tvar "a"))
*Main> run (EAbs x (EApp (EAnno (EVar x) ty) (EVar x)))
"typesynth([], λx. (x : ∀ a. a → a) x)
   typecheck([▶ 'a, ∃ 'a, ∃ 'b, $a : ∃ 'a], ($a : ∀ a. a → a) $a, ∃ 'b)
      typesynth([▶ 'a, ∃ 'a, ∃ 'b, $a : ∃ 'a], ($a : ∀ a. a → a) $a)
         typesynth([▶ 'a, ∃ 'a, ∃ 'b, $a : ∃ 'a], $a : ∀ a. a → a)
            typecheck([▶ 'a, ∃ 'a, ∃ 'b, $a : ∃ 'a], $a, ∀ a. a → a)
               typecheck([▶ 'a, ∃ 'a, ∃ 'b, $a : ∃ 'a, 'c], $a, 'c → 'c)
                  typesynth([▶ 'a, ∃ 'a, ∃ 'b, $a : ∃ 'a, 'c], $a)
                  =(∃ 'a, [▶ 'a, ∃ 'a, ∃ 'b, $a : ∃ 'a, 'c])
                  subtype([▶ 'a, ∃ 'a, ∃ 'b, $a : ∃ 'a, 'c], ∃ 'a, 'c → 'c)
                     instantiateL([▶ 'a, ∃ 'a, ∃ 'b, $a : ∃ 'a, 'c], 'a, 'c → 'c)
                        instantiateR([▶ 'a, ∃ 'e, ∃ 'd, ∃ 'a = ∃ 'd → ∃ 'e, ∃ 'b, $a : ∃ 'a, 'c], 'c, 'd)
*** Exception: The impossible happened! instantiateR: ([▶ 'a, ∃ 'e, ∃ 'd, ∃ 'a = ∃ 'd → ∃ 'e, ∃ 'b, $a : ∃ 'a, 'c], 'c, 'd)
*Main> 
```

where `run` is defined in a file `Main.hs` as follows:

```haskell
module Main where

import AST
import Context
import NameGen
import Pretty
import Type

import Control.Monad.State

run :: Expr -> String
run e = case runState (typesynth (context []) e) initialNameState of
  (context, _) -> pretty context
```

**Comment by ollef** [comment]
If you can find out where this error comes from (is it a bug in the transliteration of the paper?) I'll accept PRs to fix it. Cheers!

**Comment by samuela** [comment]
I'm not quite sure... I'm trying to figure it out now.

**Comment by samuela** [comment]
Ah, I think the issue here is that the `instantiateR([∃ 'e, ∃ 'd, ∃ 'a = ∃ 'd → ∃ 'e, ∃ 'b, $a : ∃ 'a, 'c], 'c, 'd)` attempts to instantiate `∃ 'd` to have type `'c`, but `'c` is not defined in the context preceding `∃ 'd`. Therefore, `solve` evaluates to `None` which make `instantiateR` throw the error.

It's not clear to me, however, whether this is an error in the code itself or in the paper. I'm tempted to believe that it's an issue with the paper, but I can't say for sure.

**Comment by samuela** [comment]
Well, it seems the real issue is that `instantiateR([...], 'c, 'd)` should be `instantiateR([...], 'c, ∃ 'd)`. However, correcting this will require some significant refactoring, since

```haskell
instantiateL :: Context -> TVar -> Polytype -> NameGen Context
instantiateR :: Context -> Polytype -> TVar -> NameGen Context
```

will have to be adjusted to something like

```haskell
instantiateL :: Context -> TExists -> Polytype -> NameGen Context
instantiateR :: Context -> Polytype -> TExists -> NameGen Context
````

and `TExists` is not currently a data type, only a constructor.

**Comment by ollef** [comment]
The issue here is that `instantiateR` gets a `TVar` as its `Polytype` argument, isn't it? I'm not sure if that should have been handled higher up the chain, or if it should be added to instantiation though.

The design you describe above sounds safer than the current design so I wouldn't be opposed to such a refactoring, but I'm not sure it would solve this problem.

**Comment by samuela** [comment]
Update from Neel Krishnawasmi via email:

```
The short answer is that this program
is failing to typecheck because our spec and our algorithm will reject
it.

If you drop the type annotation, the term you have is

  λx. x x

This is a self-application, which is well-typed in full System F. Adding
in type annotations and explicit type applications, it would look like:

  λx:∀a. a → a. x [∀a. a → a] x

This says that you should take x, and then instantiate the type parameter
with the type  ∀a. a → a, and then apply x to it.

   x : ∀a. a → a
   x [∀a. a → a] : (∀a. a → a) → (∀a. a → a)
   x [∀a. a → a] x : (∀a. a → a)

This kind of instantiation is rejected by our system. When you
instantiate a type variable, you can only instantiate it with a
*monotype* – that is, type parameters can only be filled in with types
that don't have any type variables in them. This restriction is the
same one that ML and Haskell compilers use, because it keeps the
inference problem reasonably simple.

However, it means that fewer programs are accepted than in full
System – in particular, the self-application you wrote is rejected.
```

Thanks Neel!
