### ISSUE TITLE
Is this the whole of "Complete and Easy Bidirectional Typechecking for Higher-Rank Polymorphism"?

### ISSUE THREAD

**Issue by danr** [ollef/Bidirectional#4]
Your implementation is very short!!
I'm going to study it and your code over the christmas break.

**Comment by danr** [comment]
Or is it based on this earlier paper? https://www.cs.cmu.edu/%7Ejoshuad/papers/bidir/

**Comment by ollef** [comment]
Aren't those the same? :) But yeah, that's the one!

**Comment by ollef** [comment]
Maybe you were thinking of the follow-up that covers gadts which isn't covered here.

**Comment by danr** [comment]
Yes, they are the same, I'm a bit thick :)

Hey, you're their hero: http://semantic-domain.blogspot.se/2013/04/thanks-to-olle-fredriksson.html

Is the other article you refer to this one? https://arxiv.org/abs/1601.05106

**Comment by ollef** [comment]
No worries! :)

Yes, that's the one with GADTs.

I've added a description to this repo now.

**Comment by danr** [comment]
Thanks! Closing this now then :) 

Looking forward to our hackathon btw!

**Comment by ollef** [comment]
Me too!
