### ISSUE TITLE
is the alpha-conversion in instantiation really necessary (InstLAIIR)?

### ISSUE THREAD

**Issue by msackman-synthace** [ollef/Bidirectional#6]
Hi,

I'm currently implementing these algorithms, in ... Go, of all languages, and the results are as you'd expect. Having your work as a guide is extremely useful. Thank you.

In your implementation, you do alpha-conversion of \beta as part of InstLAIIR. The text doesn't make mention that this is necessary (though I can completely believe this was something that got cut to make a page limit). Did you come across cases where this is essential?

**Comment by ollef** [comment]
Hey!

It's been a while, so I can't really remember, but since this is using strings for names it's probably necessary to do this to avoid variable capture.

**Comment by msackman-synthace** [comment]
Okie doke. Thanks for the quick reply. I saw a comment from them on their blog where they make reference to the fact they're a little casual with alpha-conversions in the paper, so I can well believe it.
Makes it tempting to switch to de Bruijn indices.

**Comment by ollef** [comment]
Yeah, I expect most "proper" implementations would do something like that to avoid capture problems.
